import Head from "next/head";
import Navbar from "../components/Navbar";
import { UserAuth, UserContext } from "../context/AuthContext";
import { useContext } from "react";
import Hero from "../components/Hero";
export default function Home() {
  const { createUser } = useContext(UserContext);

  const makeNewUserUsingFirebaseAuthContext = async () => {
    try{
      const data = await createUser("jinishshah08@gmail.com", "123456");
      console.log(data)
    }
    catch(err){
      if(err.message === "Firebase: Error (auth/email-already-in-use)."){
        console.log("Email already exists")
      }
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
    </div>
  );
}
