import Head from "next/head";
import Navbar from "../components/Navbar";
import { UserAuth, UserContext } from "../context/AuthContext";
import { useContext, useEffect } from "react";
import Hero from "../components/Hero";
import Calender from "../components/calendar/Calender";
import { app } from "../utils/firebase-config";
import { getDatabase, onValue, ref, set } from "firebase/database";

export default function Home() {
  const { createUser } = useContext(UserContext);

  const makeNewUserUsingFirebaseAuthContext = async () => {
    try {
      const data = await createUser("jinishshah08@gmail.com", "123456");
      console.log(data);
    } catch (err) {
      if (err.message === "Firebase: Error (auth/email-already-in-use).") {
        console.log("Email already exists");
      }
    }
  };

  const updateRealTimeDatabase = () => {
    const db = getDatabase()
    set(ref(db, '1234/'), {
      name:"jinish"
    })
  }

  const readDataFromRealTimeDatabase = () => {
    const db = getDatabase();
    const starCountRef = ref(db, "user/");
    onValue(starCountRef, (snapshot) => {
    const data = snapshot.val();
    // updateStarCount(postElement, data);
    console.log(data)
  });
  }

  useEffect(()=>{
    // updateRealTimeDatabase()
    readDataFromRealTimeDatabase()
  },[])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
    </div>
  );
}
